/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

import { MaterialGreen, MaterialRed, MaterialWater } from "../materials";

const Miyajima = () => {
  const { nodes } = useGLTF("/planets/miyajima.gltf") as unknown as {
    nodes: {
      water: THREE.Mesh;
      green: THREE.Mesh;
      red: THREE.Mesh;
    };
  };

  const [ref, setRef] = useState<THREE.Group | null>(null);

  useFrame(() => {
    if (ref) {
      const x = ref.rotation.x + 0.0005;
      const y = ref.rotation.y + 0.002;
      const z = ref.rotation.z + 0.0005;
      ref.rotation.set(x, y, z);
    }
  });
  return (
    <group scale={8} position={[-66.5, 28, -50]} ref={(e) => setRef(e)}>
      <mesh geometry={nodes.water.geometry}>
        <MaterialWater />
      </mesh>
      <mesh geometry={nodes.green.geometry}>
        <MaterialGreen />
      </mesh>
      <mesh geometry={nodes.red.geometry}>
        <MaterialRed />
      </mesh>
    </group>
  );
};

export default Miyajima;
