/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

import { MaterialGreen, MaterialRed, MaterialWater } from "../materials";

const Miyajima = () => {
  const { nodes } = useGLTF("/planets/miyajima.gltf");

  const ref: null | { current: THREE.Mesh } = useRef();

  useFrame(() => {
    if (ref) {
      const x = ref.current.rotation.x + 0.0005;
      const y = ref.current.rotation.y + 0.002;
      const z = ref.current.rotation.z + 0.0005;
      ref.current.rotation.set(x, y, z);
    }
  });
  return (
    <group scale={8} position={[-66.5, 28, -50]} ref={ref}>
      <mesh geometry={nodes.water.geometry}>
        <useMaterialWater />
      </mesh>
      <mesh geometry={nodes.green.geometry}>
        <useMaterialGreen />
      </mesh>
      <mesh geometry={nodes.red.geometry}>
        <useMaterialRed />
      </mesh>
    </group>
  );
};

export default Miyajima;
