/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

import { MaterialGreen, MaterialRed, MaterialWater } from "../materials";
import { rotatePlanetOrStar } from "./constants";
import { breakpoints } from "@/models";
import { useAppSelector } from "@/store";

const Miyajima = () => {
  const { nodes } = useGLTF("/planets/miyajima.gltf") as unknown as {
    nodes: {
      water: THREE.Mesh;
      green: THREE.Mesh;
      red: THREE.Mesh;
    };
  };

  const [ref, setRef] = useState<THREE.Group | null>(null);
  const { width } = useAppSelector((state) => state.system);
  useFrame(() => {
    rotatePlanetOrStar(ref, {
      x: 0.0005,
      y: 0.002,
      z: 0.0005,
    });
  });
  return (
    <group
      scale={8}
      position={width >= breakpoints.sm ? [-66.5, 28, -50] : [-10.5, 40, -60]}
      ref={(e) => setRef(e)}
    >
      <mesh geometry={nodes.water.geometry}>
        <MaterialWater />
      </mesh>
      <mesh geometry={nodes.green.geometry}>
        <MaterialGreen />
      </mesh>
      <mesh geometry={nodes.red.geometry}>
        <MaterialRed />
      </mesh>
    </group>
  );
};

export default Miyajima;
