/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

import {
  MaterialBlue,
  MaterialGlass,
  MaterialYellow,
  MaterialGreen,
  MaterialRed,
  MaterialWater,
  MaterialWhite,
} from "../materials";

const Sintra = () => {
  const { nodes } = useGLTF("/planets/sintra.gltf");

  const ref = useRef() as null | { current: THREE.Mesh };

  useFrame(() => {
    if (ref) {
      const x = ref.current.rotation.x + 0.0005;
      const y = ref.current.rotation.y + 0.002;
      const z = ref.current.rotation.z + 0.0005;
      ref.current.rotation.set(0, y, 0);
    }
  });
  return (
    <group dispose={null}>
      <group position={[-45, -40, -45]} scale={12} ref={ref}>
        <mesh geometry={nodes.glassDarkBlue.geometry}>
          <MaterialGlass.BlueDark />
        </mesh>
        <mesh geometry={nodes.glassRed.geometry}>
          <MaterialGlass.Red />
        </mesh>
        <mesh geometry={nodes.blue.geometry}>
          <useMaterialBlue />
        </mesh>
        <mesh geometry={nodes.water.geometry}>
          <useMaterialWater />
        </mesh>
        <mesh geometry={nodes.glassGreen.geometry}>
          <MaterialGlass.Green />
        </mesh>
        <mesh geometry={nodes.yellow.geometry}>
          <useMaterialYellow />
        </mesh>
        <mesh geometry={nodes.glassWhite.geometry}>
          <MaterialGlass.White />
        </mesh>
        <mesh geometry={nodes.white.geometry}>
          <useMaterialWhite />
        </mesh>
        <mesh geometry={nodes.green.geometry}>
          <useMaterialGreen />
        </mesh>
        <mesh geometry={nodes.red.geometry}>
          <useMaterialRed />
        </mesh>
      </group>
    </group>
  );
};

export default Sintra;
