export const clientIds = {
  adidas: "adidas",
  bahlsen: "bahlsen",
  bsr: "bsr",
  bundesliga: "bundesliga",
  bvr: "bvr",
  carlsen: "carlsen",
  eBay: "eBay",
  ferrero: "ferrero",
  forumNewEconomy: "forumNewEconomy",
  fraunhofer: "fraunhofer",
  fraunhoferIao: "fraunhoferIao",
  leopoldina: "leopoldina",
  mateMate: "mateMate",
  mdr: "mdr",
  netflix: "netflix",
  qi2: "qi2",
  rundfunkSinfonieOrchester: "rundfunkSinfonieOrchester",
  StiftungKunstUndNatur: "StiftungKunstUndNatur",
  swatch: "swatch",
  thomasHenry: "thomasHenry",
  zalando: "zalando",
};
